### ISSUE TITLE
[IDEA] Correct RTL support for Tiddlywiki

### ISSUE THREAD

**Issue by kookma** [dalirnet/rtl-markdown#1]
Does the RTL-markdown and in better way RTL text-area edit can be used in Tiddlywiki

See
https://github.com/Jermolene/TiddlyWiki5/issues/2976

**Comment by dalirnet** [comment]
با ابزار مذکور آشنایی ندارم, منتها یه بررسی کردم دیدم خودتون به بهترین روش انجام دادید
