### ISSUE TITLE
Is this project yet on , or it is abandoned ? 

### ISSUE THREAD

**Issue by Korak-997** [dalirnet/rtl-markdown#2]
I was so happy to find out that there is kind of support for **RTL** languages . 
Unfortunately , the extension is having problems after installation . It does not run and keeps asking to be installed even thought it is already installed. 

Is there anyway to fix that ?

**Comment by dalirnet** [comment]
Thanks for your kind.

##### Please check this steps:
- Update to last version of VSCode.
- After Install the plugin active it with command `Active RTL-Markdown`.
- Restart VSCode for change to take effect. (this plugin change VSCode core files)
- Ignore VSCode warning about core changes.
- Change your file name ext to `.rtl.md` for example `list.md` to `list.rtl.md`.
- Now you should see RTL layout of your markdown file.

**Comment by Korak-997** [comment]
Thanks a lot for your answer , i will look forward to try it and will give my feedback again .

**Comment by dalirnet** [comment]
I just update ([v0.0.7](https://github.com/dalirnet/rtl-markdown/commit/440f6cb5af14a99239c086d0b7db2b0c6e34d75c)) the plugin and rename `install` command to `active` to prevent misunderstanding.
