### ISSUE TITLE
¨rtl markdown¨ cannot be active!

### ISSUE THREAD

**Issue by farzin-az** [dalirnet/rtl-markdown#4]
When I run "Active RTL Markdown" I run to the above-mentioned error.
vscode version: 1.63.2
rtl markdown version: 0.0.8

**Comment by dalirnet** [comment]
Please try updating to the latest version [0.0.9](https://github.com/dalirnet/rtl-markdown/releases/download/0.0.9/rtl-markdown-0.0.9.vsix) and if it still does not work, please follow these steps:

1. Toggle developer tools `Menu Bar > Help > Toggle Developer Tools`
2. Switch to `Console` tab
3. Filter logs by `rtl-markdown`
4. Copy all logs and put them here

**Comment by farzin-az** [comment]
I updated to 0.0.9, but the problem persisted. This is the log by the way:
I use linux (NixOS) if it helps in debugging.
> [Extension Host] rtl-markdown Error: Unable to find pkexec or kdesudo.
>     at test (/home/farzin/.vscode/extensions/dalirnet.rtl-markdown-0.0.9/node_modules/sudo-prompt/index.js:205:18)
>     at /home/farzin/.vscode/extensions/dalirnet.rtl-markdown-0.0.9/node_modules/sudo-prompt/index.js:212:47
>     at FSReqCallback.oncomplete (fs.js:183:21)
> notificationsAlerts.ts:42 "RTL Markdown" cannot be active!
> onDidChangeNotification @ notificationsAlerts.ts:42
> (anonymous) @ notificationsAlerts.ts:28
> fire @ event.ts:577
> addNotification @ notifications.ts:206
> notify @ notificationService.ts:137
> (anonymous) @ mainThreadMessageService.ts:86
> _showMessage @ mainThreadMessageService.ts:44
> $showMessage @ mainThreadMessageService.ts:38
> _doInvokeHandler @ rpcProtocol.ts:472
> _invokeHandler @ rpcProtocol.ts:457
> _receiveRequest @ rpcProtocol.ts:373
> _receiveOneMessage @ rpcProtocol.ts:295
> (anonymous) @ rpcProtocol.ts:160
> fire @ event.ts:577
> fire @ ipc.net.ts:638
> _receiveMessage @ ipc.net.ts:958
> (anonymous) @ ipc.net.ts:831
> fire @ event.ts:577
> acceptChunk @ ipc.net.ts:382
> (anonymous) @ ipc.net.ts:338
> P @ ipc.net.ts:60
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188

**Comment by dalirnet** [comment]
**NixOS** may not support *kdesudo* or *pkexec* which [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) requires.

[node_modules/sudo-prompt/index.js](https://github.com/jorangreef/sudo-prompt/blob/c3cc31a51bc50fe21fadcbf76a88609c0c77026f/index.js#L198)
```js
function LinuxBinary(instance, end) {
  var index = 0;
  // We used to prefer gksudo over pkexec since it enabled a better prompt.
  // However, gksudo cannot run multiple commands concurrently.
  var paths = ['/usr/bin/kdesudo', '/usr/bin/pkexec'];
  function test() {
    if (index === paths.length) {
      return end(new Error('Unable to find pkexec or kdesudo.'));
    }
    var path = paths[index++];
    Node.fs.stat(path,
      function(error) {
        if (error) {
          if (error.code === 'ENOTDIR') return test();
          if (error.code === 'ENOENT') return test();
          end(error);
        } else {
          end(undefined, path);
        }
      }
    );
  }
  test();
}
```

I will continue to look for solutions.

**Comment by dalirnet** [comment]
I added new option to activate without `sudo-prompt`, so please 
- Upgrade to version [0.0.10](https://github.com/dalirnet/rtl-markdown/releases/download/0.0.10/rtl-markdown-0.0.10.vsix)
- Run `vscode` as root
- Use `regular` button to activation
