### ISSUE TITLE
Hope to provide an entry to specify user local CSS

### ISSUE THREAD

**Issue by SilvaQ** [dalirnet/rtl-markdown#5]
Hope to provide an entry to specify user local CSS to make customization easier.
For example, in my scene, I also want to adjust the font, color and other information。

[shirkhan-vscode](https://github.com/ishirkhan/shirkhan-vscode) is a plugin I developed that shows RTL style in the webview and I thought we could add it to make writing and previewing support RTL.  font handling by user own.

**Comment by dalirnet** [comment]
Thanks for the suggestion, and I'm thinking about it.
You can also use the vs-code font settings to set a `non-English` font as a secondary parameter.

```json
{
  "settings": {
    "editor.fontFamily": "Fira Code, IRANSansXNoEn"
  }
}
```

![sample](https://user-images.githubusercontent.com/7668289/148731581-cb6552b3-8551-46cc-a6b6-74b1ab28defb.jpg)

**Comment by SilvaQ** [comment]
Because there are multiple language documents in the workspace, it is not very convenient to directly modify the original vscode font, and it is faster and more efficient to quickly turn on and off the font with commands.
